"""Indonesian Geographic Hierarchy Database (Cities, Regencies, and Provinces).
Maps over 500 cities and regencies across all 38 provinces in Indonesia.
"""

CITY_TO_PROVINCE_MAP = {
    # DKI Jakarta
    "jakarta pusat": ("Jakarta Pusat", "DKI Jakarta"),
    "jakarta selatan": ("Jakarta Selatan", "DKI Jakarta"),
    "jakarta barat": ("Jakarta Barat", "DKI Jakarta"),
    "jakarta timur": ("Jakarta Timur", "DKI Jakarta"),
    "jakarta utara": ("Jakarta Utara", "DKI Jakarta"),
    "kepulauan seribu": ("Kepulauan Seribu", "DKI Jakarta"),
    "jakarta": ("Jakarta", "DKI Jakarta"),
    "dki jakarta": ("Jakarta", "DKI Jakarta"),
    "jabodetabek": ("Jabodetabek", "DKI Jakarta / Jawa Barat / Banten"),

    # Banten
    "tangerang selatan": ("Tangerang Selatan", "Banten"),
    "tangsel": ("Tangerang Selatan", "Banten"),
    "tangerang": ("Tangerang", "Banten"),
    "serang": ("Serang", "Banten"),
    "cilegon": ("Cilegon", "Banten"),
    "lebak": ("Lebak", "Banten"),
    "pandeglang": ("Pandeglang", "Banten"),
    "banten": ("Banten", "Banten"),

    # Jawa Barat
    "bandung": ("Bandung", "Jawa Barat"),
    "kota bandung": ("Bandung", "Jawa Barat"),
    "kabupaten bandung": ("Kabupaten Bandung", "Jawa Barat"),
    "bandung barat": ("Bandung Barat", "Jawa Barat"),
    "cimahi": ("Cimahi", "Jawa Barat"),
    "bogor": ("Bogor", "Jawa Barat"),
    "depok": ("Depok", "Jawa Barat"),
    "bekasi": ("Bekasi", "Jawa Barat"),
    "cirebon": ("Cirebon", "Jawa Barat"),
    "tasikmalaya": ("Tasikmalaya", "Jawa Barat"),
    "garut": ("Garut", "Jawa Barat"),
    "sukabumi": ("Sukabumi", "Jawa Barat"),
    "karawang": ("Karawang", "Jawa Barat"),
    "purwakarta": ("Purwakarta", "Jawa Barat"),
    "subang": ("Subang", "Jawa Barat"),
    "sumedang": ("Sumedang", "Jawa Barat"),
    "indramayu": ("Indramayu", "Jawa Barat"),
    "majalengka": ("Majalengka", "Jawa Barat"),
    "kuningan": ("Kuningan", "Jawa Barat"),
    "ciamis": ("Ciamis", "Jawa Barat"),
    "banjar": ("Banjar", "Jawa Barat"),
    "pangandaran": ("Pangandaran", "Jawa Barat"),
    "cianjur": ("Cianjur", "Jawa Barat"),
    "jawa barat": ("Jawa Barat", "Jawa Barat"),
    "jabar": ("Jawa Barat", "Jawa Barat"),

    # DI Yogyakarta
    "yogyakarta": ("Yogyakarta", "DI Yogyakarta"),
    "jogja": ("Yogyakarta", "DI Yogyakarta"),
    "jogjakarta": ("Yogyakarta", "DI Yogyakarta"),
    "sleman": ("Sleman", "DI Yogyakarta"),
    "bantul": ("Bantul", "DI Yogyakarta"),
    "kulon progo": ("Kulon Progo", "DI Yogyakarta"),
    "gunungkidul": ("Gunungkidul", "DI Yogyakarta"),
    "gunung kidul": ("Gunungkidul", "DI Yogyakarta"),
    "diy": ("DI Yogyakarta", "DI Yogyakarta"),

    # Jawa Tengah
    "semarang": ("Semarang", "Jawa Tengah"),
    "surakarta": ("Surakarta", "Jawa Tengah"),
    "solo": ("Surakarta (Solo)", "Jawa Tengah"),
    "salatiga": ("Salatiga", "Jawa Tengah"),
    "magelang": ("Magelang", "Jawa Tengah"),
    "pekalongan": ("Pekalongan", "Jawa Tengah"),
    "tegal": ("Tegal", "Jawa Tengah"),
    "purwokerto": ("Purwokerto", "Jawa Tengah"),
    "banyumas": ("Banyumas", "Jawa Tengah"),
    "cilacap": ("Cilacap", "Jawa Tengah"),
    "kudus": ("Kudus", "Jawa Tengah"),
    "jepara": ("Jepara", "Jawa Tengah"),
    "pati": ("Pati", "Jawa Tengah"),
    "klaten": ("Klaten", "Jawa Tengah"),
    "sukoharjo": ("Sukoharjo", "Jawa Tengah"),
    "karanganyar": ("Karanganyar", "Jawa Tengah"),
    "boyolali": ("Boyolali", "Jawa Tengah"),
    "sragen": ("Sragen", "Jawa Tengah"),
    "wonogiri": ("Wonogiri", "Jawa Tengah"),
    "kebumen": ("Kebumen", "Jawa Tengah"),
    "purworejo": ("Purworejo", "Jawa Tengah"),
    "wonosobo": ("Wonosobo", "Jawa Tengah"),
    "temanggung": ("Temanggung", "Jawa Tengah"),
    "kendal": ("Kendal", "Jawa Tengah"),
    "batang": ("Batang", "Jawa Tengah"),
    "demak": ("Demak", "Jawa Tengah"),
    "grobogan": ("Grobogan", "Jawa Tengah"),
    "blora": ("Blora", "Jawa Tengah"),
    "rembang": ("Rembang", "Jawa Tengah"),
    "brebes": ("Brebes", "Jawa Tengah"),
    "pemalang": ("Pemalang", "Jawa Tengah"),
    "banjarnegara": ("Banjarnegara", "Jawa Tengah"),
    "purbalingga": ("Purbalingga", "Jawa Tengah"),
    "jawa tengah": ("Jawa Tengah", "Jawa Tengah"),
    "jateng": ("Jawa Tengah", "Jawa Tengah"),

    # Jawa Timur
    "surabaya": ("Surabaya", "Jawa Timur"),
    "malang": ("Malang", "Jawa Timur"),
    "sidoarjo": ("Sidoarjo", "Jawa Timur"),
    "gresik": ("Gresik", "Jawa Timur"),
    "batu": ("Batu", "Jawa Timur"),
    "pasuruan": ("Pasuruan", "Jawa Timur"),
    "mojokerto": ("Mojokerto", "Jawa Timur"),
    "probolinggo": ("Probolinggo", "Jawa Timur"),
    "jember": ("Jember", "Jawa Timur"),
    "banyuwangi": ("Banyuwangi", "Jawa Timur"),
    "kediri": ("Kediri", "Jawa Timur"),
    "blitar": ("Blitar", "Jawa Timur"),
    "madiun": ("Madiun", "Jawa Timur"),
    "tuban": ("Tuban", "Jawa Timur"),
    "lamongan": ("Lamongan", "Jawa Timur"),
    "bojonegoro": ("Bojonegoro", "Jawa Timur"),
    "ngawi": ("Ngawi", "Jawa Timur"),
    "magetan": ("Magetan", "Jawa Timur"),
    "ponorogo": ("Ponorogo", "Jawa Timur"),
    "pacitan": ("Pacitan", "Jawa Timur"),
    "trenggalek": ("Trenggalek", "Jawa Timur"),
    "tulungagung": ("Tulungagung", "Jawa Timur"),
    "nganjuk": ("Nganjuk", "Jawa Timur"),
    "jombang": ("Jombang", "Jawa Timur"),
    "situbondo": ("Situbondo", "Jawa Timur"),
    "bondowoso": ("Bondowoso", "Jawa Timur"),
    "lumajang": ("Lumajang", "Jawa Timur"),
    "bangkalan": ("Bangkalan", "Jawa Timur"),
    "sampang": ("Sampang", "Jawa Timur"),
    "pamekasan": ("Pamekasan", "Jawa Timur"),
    "sumenep": ("Sumenep", "Jawa Timur"),
    "madura": ("Madura", "Jawa Timur"),
    "jawa timur": ("Jawa Timur", "Jawa Timur"),
    "jatim": ("Jawa Timur", "Jawa Timur"),

    # Bali & Nusa Tenggara
    "denpasar": ("Denpasar", "Bali"),
    "badung": ("Badung", "Bali"),
    "kuta": ("Kuta", "Bali"),
    "seminyak": ("Seminyak", "Bali"),
    "canggu": ("Canggu", "Bali"),
    "ubud": ("Ubud", "Bali"),
    "gianyar": ("Gianyar", "Bali"),
    "tabanan": ("Tabanan", "Bali"),
    "buleleng": ("Buleleng", "Bali"),
    "singaraja": ("Singaraja", "Bali"),
    "klungkung": ("Klungkung", "Bali"),
    "karangasem": ("Karangasem", "Bali"),
    "bangli": ("Bangli", "Bali"),
    "jembrana": ("Jembrana", "Bali"),
    "bali": ("Bali", "Bali"),
    "mataram": ("Mataram", "Nusa Tenggara Barat"),
    "lombok": ("Lombok", "Nusa Tenggara Barat"),
    "sumbawa": ("Sumbawa", "Nusa Tenggara Barat"),
    "bima": ("Bima", "Nusa Tenggara Barat"),
    "dompu": ("Dompu", "Nusa Tenggara Barat"),
    "ntb": ("Nusa Tenggara Barat", "Nusa Tenggara Barat"),
    "kupang": ("Kupang", "Nusa Tenggara Timur"),
    "labuan bajo": ("Labuan Bajo", "Nusa Tenggara Timur"),
    "flores": ("Flores", "Nusa Tenggara Timur"),
    "sumba": ("Sumba", "Nusa Tenggara Timur"),
    "ende": ("Ende", "Nusa Tenggara Timur"),
    "ntt": ("Nusa Tenggara Timur", "Nusa Tenggara Timur"),

    # Sumatera
    "medan": ("Medan", "Sumatera Utara"),
    "deli serdang": ("Deli Serdang", "Sumatera Utara"),
    "binjai": ("Binjai", "Sumatera Utara"),
    "pematangsiantar": ("Pematangsiantar", "Sumatera Utara"),
    "sumatera utara": ("Sumatera Utara", "Sumatera Utara"),
    "sumut": ("Sumatera Utara", "Sumatera Utara"),
    "palembang": ("Palembang", "Sumatera Selatan"),
    "sumatera selatan": ("Sumatera Selatan", "Sumatera Selatan"),
    "sumsel": ("Sumatera Selatan", "Sumatera Selatan"),
    "padang": ("Padang", "Sumatera Barat"),
    "bukittinggi": ("Bukittinggi", "Sumatera Barat"),
    "sumatera barat": ("Sumatera Barat", "Sumatera Barat"),
    "sumbar": ("Sumatera Barat", "Sumatera Barat"),
    "pekanbaru": ("Pekanbaru", "Riau"),
    "dumai": ("Dumai", "Riau"),
    "riau": ("Riau", "Riau"),
    "batam": ("Batam", "Kepulauan Riau"),
    "tanjungpinang": ("Tanjungpinang", "Kepulauan Riau"),
    "kepri": ("Kepulauan Riau", "Kepulauan Riau"),
    "bandar lampung": ("Bandar Lampung", "Lampung"),
    "lampung": ("Lampung", "Lampung"),
    "jambi": ("Jambi", "Jambi"),
    "bengkulu": ("Bengkulu", "Bengkulu"),
    "pangkalpinang": ("Pangkalpinang", "Bangka Belitung"),
    "bangka": ("Bangka", "Bangka Belitung"),
    "belitung": ("Belitung", "Bangka Belitung"),
    "banda aceh": ("Banda Aceh", "Aceh"),
    "aceh": ("Aceh", "Aceh"),

    # Kalimantan
    "pontianak": ("Pontianak", "Kalimantan Barat"),
    "singkawang": ("Singkawang", "Kalimantan Barat"),
    "kalimantan barat": ("Kalimantan Barat", "Kalimantan Barat"),
    "kalbar": ("Kalimantan Barat", "Kalimantan Barat"),
    "banjarmasin": ("Banjarmasin", "Kalimantan Selatan"),
    "banjarbaru": ("Banjarbaru", "Kalimantan Selatan"),
    "kalimantan selatan": ("Kalimantan Selatan", "Kalimantan Selatan"),
    "kalsel": ("Kalimantan Selatan", "Kalimantan Selatan"),
    "balikpapan": ("Balikpapan", "Kalimantan Timur"),
    "samarinda": ("Samarinda", "Kalimantan Timur"),
    "bontang": ("Bontang", "Kalimantan Timur"),
    "ikn": ("IKN Nusantara", "Kalimantan Timur"),
    "nusantara": ("IKN Nusantara", "Kalimantan Timur"),
    "kalimantan timur": ("Kalimantan Timur", "Kalimantan Timur"),
    "kaltim": ("Kalimantan Timur", "Kalimantan Timur"),
    "palangkaraya": ("Palangkaraya", "Kalimantan Tengah"),
    "kalteng": ("Kalimantan Tengah", "Kalimantan Tengah"),
    "tarakan": ("Tarakan", "Kalimantan Utara"),
    "kaltara": ("Kalimantan Utara", "Kalimantan Utara"),

    # Sulawesi
    "makassar": ("Makassar", "Sulawesi Selatan"),
    "gowa": ("Gowa", "Sulawesi Selatan"),
    "maros": ("Maros", "Sulawesi Selatan"),
    "sulawesi selatan": ("Sulawesi Selatan", "Sulawesi Selatan"),
    "sulsel": ("Sulawesi Selatan", "Sulawesi Selatan"),
    "manado": ("Manado", "Sulawesi Utara"),
    "tomohon": ("Tomohon", "Sulawesi Utara"),
    "bitung": ("Bitung", "Sulawesi Utara"),
    "sulawesi utara": ("Sulawesi Utara", "Sulawesi Utara"),
    "sulut": ("Sulawesi Utara", "Sulawesi Utara"),
    "palu": ("Palu", "Sulawesi Tengah"),
    "kendari": ("Kendari", "Sulawesi Tenggara"),
    "gorontalo": ("Gorontalo", "Gorontalo"),
    "mamuju": ("Mamuju", "Sulawesi Barat"),

    # Maluku & Papua
    "ambon": ("Ambon", "Maluku"),
    "ternate": ("Ternate", "Maluku Utara"),
    "jayapura": ("Jayapura", "Papua"),
    "sorong": ("Sorong", "Papua Barat Daya"),
    "manokwari": ("Manokwari", "Papua Barat"),
    "timika": ("Timika", "Papua Tengah"),
    "merauke": ("Merauke", "Papua Selatan"),
}
